import os
import datetime

def save_md(response_text: str):
    f"""Export travel plan to Markdown file with proper formatting"""

    # Create markdown content with metadata header
    markdown_content = f"""# 🌍 AI Travel Plan

    # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
    # **Created by:** Ayad's Travel Agent

    ---

    {response_text}

    ---

    *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
    """
            
    # Write to markdown file with UTF-8 encoding
    # Generate timestamp-based filename

    out_dir = 'output'
    os.makedirs('output', exist_ok=True)
    
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"{out_dir}/completion_{timestamp}.md"

    with open(filename, 'w', encoding = 'utf-8') as f:
        f.write(markdown_content)

    return filename